
package com.docusign.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 */
@WebService(name = "APIServiceSoap", targetNamespace = "http://www.docusign.net/API/3.0")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface APIServiceSoap {


    /**
     * @param envelope
     * @return returns com.docusign.model.EnvelopeStatus
     */
    @WebMethod(operationName = "CreateEnvelope", action = "http://www.docusign.net/API/3.0/CreateEnvelope")
    @WebResult(name = "CreateEnvelopeResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "CreateEnvelope", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.CreateEnvelope")
    @ResponseWrapper(localName = "CreateEnvelopeResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.CreateEnvelopeResponse")
    public EnvelopeStatus createEnvelope(
            @WebParam(name = "Envelope", targetNamespace = "http://www.docusign.net/API/3.0")
            Envelope envelope);

    /**
     * @param envelope
     * @return returns com.docusign.model.EnvelopeStatus
     */
    @WebMethod(operationName = "CreateAndSendEnvelope", action = "http://www.docusign.net/API/3.0/CreateAndSendEnvelope")
    @WebResult(name = "CreateAndSendEnvelopeResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "CreateAndSendEnvelope", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.CreateAndSendEnvelope")
    @ResponseWrapper(localName = "CreateAndSendEnvelopeResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.CreateAndSendEnvelopeResponse")
    public EnvelopeStatus createAndSendEnvelope(
            @WebParam(name = "Envelope", targetNamespace = "http://www.docusign.net/API/3.0")
            Envelope envelope);

    /**
     * @param accountId
     * @param envelopeId
     * @return returns com.docusign.model.EnvelopeStatus
     */
    @WebMethod(operationName = "SendEnvelope", action = "http://www.docusign.net/API/3.0/SendEnvelope")
    @WebResult(name = "SendEnvelopeResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "SendEnvelope", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.SendEnvelope")
    @ResponseWrapper(localName = "SendEnvelopeResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.SendEnvelopeResponse")
    public EnvelopeStatus sendEnvelope(
            @WebParam(name = "EnvelopeId", targetNamespace = "http://www.docusign.net/API/3.0")
            String envelopeId,
            @WebParam(name = "AccountId", targetNamespace = "http://www.docusign.net/API/3.0")
            String accountId);

    /**
     * @param correction
     * @return returns com.docusign.model.CorrectionStatus
     */
    @WebMethod(operationName = "CorrectAndResendEnvelope", action = "http://www.docusign.net/API/3.0/CorrectAndResendEnvelope")
    @WebResult(name = "CorrectAndResendEnvelopeResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "CorrectAndResendEnvelope", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.CorrectAndResendEnvelope")
    @ResponseWrapper(localName = "CorrectAndResendEnvelopeResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.CorrectAndResendEnvelopeResponse")
    public CorrectionStatus correctAndResendEnvelope(
            @WebParam(name = "Correction", targetNamespace = "http://www.docusign.net/API/3.0")
            Correction correction);

    /**
     * @param envelopeID
     * @return returns com.docusign.model.EnvelopePDF
     */
    @WebMethod(operationName = "RequestPDFNoWaterMark", action = "http://www.docusign.net/API/3.0/RequestPDFNoWaterMark")
    @WebResult(name = "RequestPDFNoWaterMarkResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestPDFNoWaterMark", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestPDFNoWaterMark")
    @ResponseWrapper(localName = "RequestPDFNoWaterMarkResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestPDFNoWaterMarkResponse")
    public EnvelopePDF requestPDFNoWaterMark(
            @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
            String envelopeID);

    /**
     * @param pdfOptions
     * @param envelopeID
     * @return returns com.docusign.model.EnvelopePDF
     */
    @WebMethod(operationName = "RequestPDFWithOptions", action = "http://www.docusign.net/API/3.0/RequestPDFWithOptions")
    @WebResult(name = "RequestPDFWithOptionsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestPDFWithOptions", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestPDFWithOptions")
    @ResponseWrapper(localName = "RequestPDFWithOptionsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestPDFWithOptionsResponse")
    public EnvelopePDF requestPDFWithOptions(
            @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
            String envelopeID,
            @WebParam(name = "PDFOptions", targetNamespace = "http://www.docusign.net/API/3.0")
            PDFOptions pdfOptions);

    /**
     * @param pdFsOptions
     * @param envelopeID
     * @return returns com.docusign.model.DocumentPDFs
     */
    @WebMethod(operationName = "RequestPDFsWithOptions", action = "http://www.docusign.net/API/3.0/RequestPDFsWithOptions")
    @WebResult(name = "RequestPDFsWithOptionsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestPDFsWithOptions", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestPDFsWithOptions")
    @ResponseWrapper(localName = "RequestPDFsWithOptionsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestPDFsWithOptionsResponse")
    public DocumentPDFs requestPDFsWithOptions(
            @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
            String envelopeID,
            @WebParam(name = "PDFsOptions", targetNamespace = "http://www.docusign.net/API/3.0")
            PDFsOptions pdFsOptions);

    /**
     * @param envelopeID
     * @return returns com.docusign.model.EnvelopePDF
     */
    @WebMethod(operationName = "RequestPDF", action = "http://www.docusign.net/API/3.0/RequestPDF")
    @WebResult(name = "RequestPDFResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestPDF", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestPDF")
    @ResponseWrapper(localName = "RequestPDFResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestPDFResponse")
    public EnvelopePDF requestPDF(
            @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
            String envelopeID);

    /**
     * @param addWaterMark
     * @param envelopeID
     * @return returns com.docusign.model.EnvelopePDF
     */
    @WebMethod(operationName = "RequestPDFWithCert", action = "http://www.docusign.net/API/3.0/RequestPDFWithCert")
    @WebResult(name = "RequestPDFWithCertResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestPDFWithCert", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestPDFWithCert")
    @ResponseWrapper(localName = "RequestPDFWithCertResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestPDFWithCertResponse")
    public EnvelopePDF requestPDFWithCert(
            @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
            String envelopeID,
            @WebParam(name = "AddWaterMark", targetNamespace = "http://www.docusign.net/API/3.0")
            boolean addWaterMark);

    /**
     * @param envelopeID
     * @return returns com.docusign.model.DocumentPDFs
     */
    @WebMethod(operationName = "RequestDocumentPDFs", action = "http://www.docusign.net/API/3.0/RequestDocumentPDFs")
    @WebResult(name = "RequestDocumentPDFsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestDocumentPDFs", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestDocumentPDFs")
    @ResponseWrapper(localName = "RequestDocumentPDFsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestDocumentPDFsResponse")
    public DocumentPDFs requestDocumentPDFs(
            @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
            String envelopeID);

    /**
     * @param envelopeID
     * @return returns com.docusign.model.DocumentPDFs
     */
    @WebMethod(operationName = "RequestDocumentPDFsEx", action = "http://www.docusign.net/API/3.0/RequestDocumentPDFsEx")
    @WebResult(name = "RequestDocumentPDFsExResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestDocumentPDFsEx", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestDocumentPDFsEx")
    @ResponseWrapper(localName = "RequestDocumentPDFsExResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestDocumentPDFsExResponse")
    public DocumentPDFs requestDocumentPDFsEx(
            @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
            String envelopeID);

    /**
     * @param recipientName
     * @param envelopeID
     * @param recipientEmail
     * @return returns com.docusign.model.DocumentPDFs
     */
    @WebMethod(operationName = "RequestDocumentPDFsRecipientsView", action = "http://www.docusign.net/API/3.0/RequestDocumentPDFsRecipientsView")
    @WebResult(name = "RequestDocumentPDFsRecipientsViewResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestDocumentPDFsRecipientsView", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestDocumentPDFsRecipientsView")
    @ResponseWrapper(localName = "RequestDocumentPDFsRecipientsViewResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestDocumentPDFsRecipientsViewResponse")
    public DocumentPDFs requestDocumentPDFsRecipientsView(
            @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
            String envelopeID,
            @WebParam(name = "RecipientName", targetNamespace = "http://www.docusign.net/API/3.0")
            String recipientName,
            @WebParam(name = "RecipientEmail", targetNamespace = "http://www.docusign.net/API/3.0")
            String recipientEmail);

    /**
     * @param envelopeID
     * @return returns com.docusign.model.DocumentPDFs
     */
    @WebMethod(operationName = "RequestCertificate", action = "http://www.docusign.net/API/3.0/RequestCertificate")
    @WebResult(name = "RequestCertificateResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestCertificate", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestCertificate")
    @ResponseWrapper(localName = "RequestCertificateResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestCertificateResponse")
    public DocumentPDFs requestCertificate(
            @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
            String envelopeID);

    /**
     * @param envelopeID
     * @return returns com.docusign.model.EnvelopeStatus
     */
    @WebMethod(operationName = "RequestStatusEx", action = "http://www.docusign.net/API/3.0/RequestStatusEx")
    @WebResult(name = "RequestStatusExResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestStatusEx", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestStatusEx")
    @ResponseWrapper(localName = "RequestStatusExResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestStatusExResponse")
    public EnvelopeStatus requestStatusEx(
            @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
            String envelopeID);

    /**
     * @param envelopeID
     * @return returns com.docusign.model.EnvelopeStatus
     */
    @WebMethod(operationName = "RequestStatusWithDocumentFields", action = "http://www.docusign.net/API/3.0/RequestStatusWithDocumentFields")
    @WebResult(name = "RequestStatusWithDocumentFieldsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestStatusWithDocumentFields", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestStatusWithDocumentFields")
    @ResponseWrapper(localName = "RequestStatusWithDocumentFieldsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestStatusWithDocumentFieldsResponse")
    public EnvelopeStatus requestStatusWithDocumentFields(
            @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
            String envelopeID);

    /**
     * @param envelopeStatusFilter
     * @return returns com.docusign.model.FilteredEnvelopeStatusChanges
     */
    @WebMethod(operationName = "RequestStatusCodes", action = "http://www.docusign.net/API/3.0/RequestStatusCodes")
    @WebResult(name = "RequestStatusCodesResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestStatusCodes", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestStatusCodes")
    @ResponseWrapper(localName = "RequestStatusCodesResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestStatusCodesResponse")
    public FilteredEnvelopeStatusChanges requestStatusCodes(
            @WebParam(name = "EnvelopeStatusFilter", targetNamespace = "http://www.docusign.net/API/3.0")
            EnvelopeStatusFilter envelopeStatusFilter);

    /**
     * @param envelopeID
     * @return returns com.docusign.model.EnvelopeStatus
     */
    @WebMethod(operationName = "RequestStatus", action = "http://www.docusign.net/API/3.0/RequestStatus")
    @WebResult(name = "RequestStatusResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestStatus", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestStatus")
    @ResponseWrapper(localName = "RequestStatusResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestStatusResponse")
    public EnvelopeStatus requestStatus(
            @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
            String envelopeID);

    /**
     * @param envelopeStatusChangeFilter
     * @return returns com.docusign.model.FilteredEnvelopeStatusChanges
     */
    @WebMethod(operationName = "RequestStatusChanges", action = "http://www.docusign.net/API/3.0/RequestStatusChanges")
    @WebResult(name = "RequestStatusChangesResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestStatusChanges", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestStatusChanges")
    @ResponseWrapper(localName = "RequestStatusChangesResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestStatusChangesResponse")
    public FilteredEnvelopeStatusChanges requestStatusChanges(
            @WebParam(name = "EnvelopeStatusChangeFilter", targetNamespace = "http://www.docusign.net/API/3.0")
            EnvelopeStatusChangeFilter envelopeStatusChangeFilter);

    /**
     * @param envelopeStatusFilter
     * @return returns com.docusign.model.FilteredEnvelopeStatuses
     */
    @WebMethod(operationName = "RequestStatusesEx", action = "http://www.docusign.net/API/3.0/RequestStatusesEx")
    @WebResult(name = "RequestStatusesExResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestStatusesEx", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestStatusesEx")
    @ResponseWrapper(localName = "RequestStatusesExResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestStatusesExResponse")
    public FilteredEnvelopeStatuses requestStatusesEx(
            @WebParam(name = "EnvelopeStatusFilter", targetNamespace = "http://www.docusign.net/API/3.0")
            EnvelopeStatusFilter envelopeStatusFilter);

    /**
     * @param envelopeStatusFilter
     * @return returns com.docusign.model.FilteredEnvelopeStatuses
     */
    @WebMethod(operationName = "RequestStatuses", action = "http://www.docusign.net/API/3.0/RequestStatuses")
    @WebResult(name = "RequestStatusesResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestStatuses", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestStatuses")
    @ResponseWrapper(localName = "RequestStatusesResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestStatusesResponse")
    public FilteredEnvelopeStatuses requestStatuses(
            @WebParam(name = "EnvelopeStatusFilter", targetNamespace = "http://www.docusign.net/API/3.0")
            EnvelopeStatusFilter envelopeStatusFilter);

    /**
     * @param envelopeStatusFilter
     * @return returns com.docusign.model.FilteredEnvelopeStatuses
     */
    @WebMethod(operationName = "RequestStatusesWithDocumentFields", action = "http://www.docusign.net/API/3.0/RequestStatusesWithDocumentFields")
    @WebResult(name = "RequestStatusesWithDocumentFieldsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestStatusesWithDocumentFields", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestStatusesWithDocumentFields")
    @ResponseWrapper(localName = "RequestStatusesWithDocumentFieldsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestStatusesWithDocumentFieldsResponse")
    public FilteredEnvelopeStatuses requestStatusesWithDocumentFields(
            @WebParam(name = "EnvelopeStatusFilter", targetNamespace = "http://www.docusign.net/API/3.0")
            EnvelopeStatusFilter envelopeStatusFilter);

    /**
     * @param senderAccountId
     * @param userName
     * @param recipientEmail
     * @param senderEmail
     * @return returns com.docusign.model.RecipientEsignList
     */
    @WebMethod(operationName = "GetRecipientEsignList", action = "http://www.docusign.net/API/3.0/GetRecipientEsignList")
    @WebResult(name = "GetRecipientEsignListResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "GetRecipientEsignList", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.GetRecipientEsignList")
    @ResponseWrapper(localName = "GetRecipientEsignListResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.GetRecipientEsignListResponse")
    public RecipientEsignList getRecipientEsignList(
            @WebParam(name = "UserName", targetNamespace = "http://www.docusign.net/API/3.0")
            String userName,
            @WebParam(name = "SenderEmail", targetNamespace = "http://www.docusign.net/API/3.0")
            String senderEmail,
            @WebParam(name = "SenderAccountId", targetNamespace = "http://www.docusign.net/API/3.0")
            String senderAccountId,
            @WebParam(name = "RecipientEmail", targetNamespace = "http://www.docusign.net/API/3.0")
            String recipientEmail);

    /**
     * @param senderAccountId
     * @param recipientEmail
     * @return returns com.docusign.model.RecipientList
     */
    @WebMethod(operationName = "GetRecipientList", action = "http://www.docusign.net/API/3.0/GetRecipientList")
    @WebResult(name = "GetRecipientListResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "GetRecipientList", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.GetRecipientList")
    @ResponseWrapper(localName = "GetRecipientListResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.GetRecipientListResponse")
    public RecipientList getRecipientList(
            @WebParam(name = "SenderAccountId", targetNamespace = "http://www.docusign.net/API/3.0")
            String senderAccountId,
            @WebParam(name = "RecipientEmail", targetNamespace = "http://www.docusign.net/API/3.0")
            String recipientEmail);

    /**
     * @param brandDefinitions
     * @param accountId
     * @return returns com.docusign.model.BrandResults
     */
    @WebMethod(operationName = "CreateAccountBrands", action = "http://www.docusign.net/API/3.0/CreateAccountBrands")
    @WebResult(name = "CreateAccountBrandsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "CreateAccountBrands", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.CreateAccountBrands")
    @ResponseWrapper(localName = "CreateAccountBrandsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.CreateAccountBrandsResponse")
    public BrandResults createAccountBrands(
            @WebParam(name = "AccountId", targetNamespace = "http://www.docusign.net/API/3.0")
            String accountId,
            @WebParam(name = "BrandDefinitions", targetNamespace = "http://www.docusign.net/API/3.0")
            BrandDefinitions brandDefinitions);

    /**
     * @param accountId
     * @param brandDeleteRequest
     * @return returns com.docusign.model.BrandResults
     */
    @WebMethod(operationName = "DeleteAccountBrands", action = "http://www.docusign.net/API/3.0/DeleteAccountBrands")
    @WebResult(name = "DeleteAccountBrandsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "DeleteAccountBrands", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.DeleteAccountBrands")
    @ResponseWrapper(localName = "DeleteAccountBrandsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.DeleteAccountBrandsResponse")
    public BrandResults deleteAccountBrands(
            @WebParam(name = "AccountId", targetNamespace = "http://www.docusign.net/API/3.0")
            String accountId,
            @WebParam(name = "BrandDeleteRequest", targetNamespace = "http://www.docusign.net/API/3.0")
            BrandDeleteRequest brandDeleteRequest);

    /**
     * @param accountId
     * @return returns com.docusign.model.BrandResults
     */
    @WebMethod(operationName = "GetAccountBrands", action = "http://www.docusign.net/API/3.0/GetAccountBrands")
    @WebResult(name = "GetAccountBrandsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "GetAccountBrands", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.GetAccountBrands")
    @ResponseWrapper(localName = "GetAccountBrandsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.GetAccountBrandsResponse")
    public BrandResults getAccountBrands(
            @WebParam(name = "AccountId", targetNamespace = "http://www.docusign.net/API/3.0")
            String accountId);

    /**
     * @param reason
     * @param envelopeID
     * @return returns com.docusign.model.VoidEnvelopeStatus
     */
    @WebMethod(operationName = "VoidEnvelope", action = "http://www.docusign.net/API/3.0/VoidEnvelope")
    @WebResult(name = "VoidEnvelopeResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "VoidEnvelope", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.VoidEnvelope")
    @ResponseWrapper(localName = "VoidEnvelopeResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.VoidEnvelopeResponse")
    public VoidEnvelopeStatus voidEnvelope(
            @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
            String envelopeID,
            @WebParam(name = "Reason", targetNamespace = "http://www.docusign.net/API/3.0")
            String reason);

    /**
     * @param username
     * @param email
     * @param envelopeID
     * @param clientURLs
     * @param clientUserID
     * @param authenticationAssertion
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "RequestRecipientToken", action = "http://www.docusign.net/API/3.0/RequestRecipientToken")
    @WebResult(name = "RequestRecipientTokenResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestRecipientToken", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestRecipientToken")
    @ResponseWrapper(localName = "RequestRecipientTokenResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestRecipientTokenResponse")
    public String requestRecipientToken(
            @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
            String envelopeID,
            @WebParam(name = "ClientUserID", targetNamespace = "http://www.docusign.net/API/3.0")
            String clientUserID,
            @WebParam(name = "Username", targetNamespace = "http://www.docusign.net/API/3.0")
            String username,
            @WebParam(name = "Email", targetNamespace = "http://www.docusign.net/API/3.0")
            String email,
            @WebParam(name = "AuthenticationAssertion", targetNamespace = "http://www.docusign.net/API/3.0")
            RequestRecipientTokenAuthenticationAssertion authenticationAssertion,
            @WebParam(name = "ClientURLs", targetNamespace = "http://www.docusign.net/API/3.0")
            RequestRecipientTokenClientURLs clientURLs);

    /**
     * @param username
     * @param email
     * @param envelopeID
     * @param clientURLs
     * @param clientUserID
     * @param authenticationAssertion
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "RequestRecipientFaxToken", action = "http://www.docusign.net/API/3.0/RequestRecipientFaxToken")
    @WebResult(name = "RequestRecipientFaxTokenResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestRecipientFaxToken", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestRecipientFaxToken")
    @ResponseWrapper(localName = "RequestRecipientFaxTokenResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestRecipientFaxTokenResponse")
    public String requestRecipientFaxToken(
            @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
            String envelopeID,
            @WebParam(name = "ClientUserID", targetNamespace = "http://www.docusign.net/API/3.0")
            String clientUserID,
            @WebParam(name = "Username", targetNamespace = "http://www.docusign.net/API/3.0")
            String username,
            @WebParam(name = "Email", targetNamespace = "http://www.docusign.net/API/3.0")
            String email,
            @WebParam(name = "AuthenticationAssertion", targetNamespace = "http://www.docusign.net/API/3.0")
            RequestRecipientTokenAuthenticationAssertion authenticationAssertion,
            @WebParam(name = "ClientURLs", targetNamespace = "http://www.docusign.net/API/3.0")
            RequestRecipientTokenClientURLs clientURLs);

    /**
     * @param username
     * @param email
     * @param envelopeID
     * @param clientUserID
     * @param authenticationAssertion
     * @return returns com.docusign.model.EnvelopePDF
     */
    @WebMethod(operationName = "RequestRecipientFaxPDF", action = "http://www.docusign.net/API/3.0/RequestRecipientFaxPDF")
    @WebResult(name = "RequestRecipientFaxPDFResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestRecipientFaxPDF", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestRecipientFaxPDF")
    @ResponseWrapper(localName = "RequestRecipientFaxPDFResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestRecipientFaxPDFResponse")
    public EnvelopePDF requestRecipientFaxPDF(
            @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
            String envelopeID,
            @WebParam(name = "ClientUserID", targetNamespace = "http://www.docusign.net/API/3.0")
            String clientUserID,
            @WebParam(name = "Username", targetNamespace = "http://www.docusign.net/API/3.0")
            String username,
            @WebParam(name = "Email", targetNamespace = "http://www.docusign.net/API/3.0")
            String email,
            @WebParam(name = "AuthenticationAssertion", targetNamespace = "http://www.docusign.net/API/3.0")
            RequestRecipientTokenAuthenticationAssertion authenticationAssertion);

    /**
     * @param userID
     * @param accountID
     * @param envelopeID
     * @return returns com.docusign.model.TransferEnvelopeStatus
     */
    @WebMethod(operationName = "TransferEnvelope", action = "http://www.docusign.net/API/3.0/TransferEnvelope")
    @WebResult(name = "TransferEnvelopeResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "TransferEnvelope", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.TransferEnvelope")
    @ResponseWrapper(localName = "TransferEnvelopeResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.TransferEnvelopeResponse")
    public TransferEnvelopeStatus transferEnvelope(
            @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
            String envelopeID,
            @WebParam(name = "AccountID", targetNamespace = "http://www.docusign.net/API/3.0")
            String accountID,
            @WebParam(name = "UserID", targetNamespace = "http://www.docusign.net/API/3.0")
            String userID);

    /**
     * @param accountId
     * @return returns com.docusign.model.AccountMembershipFeaturesList
     */
    @WebMethod(operationName = "GetAccountMembershipFeaturesList", action = "http://www.docusign.net/API/3.0/GetAccountMembershipFeaturesList")
    @WebResult(name = "GetAccountMembershipFeaturesListResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "GetAccountMembershipFeaturesList", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.GetAccountMembershipFeaturesList")
    @ResponseWrapper(localName = "GetAccountMembershipFeaturesListResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.GetAccountMembershipFeaturesListResponse")
    public AccountMembershipFeaturesList getAccountMembershipFeaturesList(
            @WebParam(name = "AccountId", targetNamespace = "http://www.docusign.net/API/3.0")
            String accountId);

    /**
     * @param accountId
     * @return returns com.docusign.model.AccountSettingsList
     */
    @WebMethod(operationName = "GetAccountSettingsList", action = "http://www.docusign.net/API/3.0/GetAccountSettingsList")
    @WebResult(name = "GetAccountSettingsListResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "GetAccountSettingsList", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.GetAccountSettingsList")
    @ResponseWrapper(localName = "GetAccountSettingsListResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.GetAccountSettingsListResponse")
    public AccountSettingsList getAccountSettingsList(
            @WebParam(name = "AccountId", targetNamespace = "http://www.docusign.net/API/3.0")
            String accountId);

    /**
     * @param transactionId
     * @param envelopeId
     * @param checkSumHash
     * @return returns com.docusign.model.AuthoritativeCopyExportStatus
     */
    @WebMethod(operationName = "AcknowledgeAuthoritativeCopyExport", action = "http://www.docusign.net/API/3.0/AcknowledgeAuthoritativeCopyExport")
    @WebResult(name = "AcknowledgeAuthoritativeCopyExportResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "AcknowledgeAuthoritativeCopyExport", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.AcknowledgeAuthoritativeCopyExport")
    @ResponseWrapper(localName = "AcknowledgeAuthoritativeCopyExportResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.AcknowledgeAuthoritativeCopyExportResponse")
    public AuthoritativeCopyExportStatus acknowledgeAuthoritativeCopyExport(
            @WebParam(name = "EnvelopeId", targetNamespace = "http://www.docusign.net/API/3.0")
            String envelopeId,
            @WebParam(name = "TransactionId", targetNamespace = "http://www.docusign.net/API/3.0")
            String transactionId,
            @WebParam(name = "checkSumHash", targetNamespace = "http://www.docusign.net/API/3.0")
            byte[] checkSumHash);

    /**
     * @param envelopeId
     * @return returns com.docusign.model.AuthoritativeCopyExportDocuments
     */
    @WebMethod(operationName = "ExportAuthoritativeCopy", action = "http://www.docusign.net/API/3.0/ExportAuthoritativeCopy")
    @WebResult(name = "ExportAuthoritativeCopyResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "ExportAuthoritativeCopy", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.ExportAuthoritativeCopy")
    @ResponseWrapper(localName = "ExportAuthoritativeCopyResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.ExportAuthoritativeCopyResponse")
    public AuthoritativeCopyExportDocuments exportAuthoritativeCopy(
            @WebParam(name = "EnvelopeId", targetNamespace = "http://www.docusign.net/API/3.0")
            String envelopeId);

    /**
     * @param envelopeId
     * @return returns com.docusign.model.EnvelopeAuditEventsResponse.EnvelopeAuditEventsResult
     */
    @WebMethod(operationName = "EnvelopeAuditEvents", action = "http://www.docusign.net/API/3.0/EnvelopeAuditEvents")
    @WebResult(name = "EnvelopeAuditEventsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "EnvelopeAuditEvents", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.EnvelopeAuditEvents")
    @ResponseWrapper(localName = "EnvelopeAuditEventsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.EnvelopeAuditEventsResponse")
    public com.docusign.model.EnvelopeAuditEventsResponse.EnvelopeAuditEventsResult envelopeAuditEvents(
            @WebParam(name = "EnvelopeId", targetNamespace = "http://www.docusign.net/API/3.0")
            String envelopeId);

    /**
     * @return returns boolean
     */
    @WebMethod(operationName = "Ping", action = "http://www.docusign.net/API/3.0/Ping")
    @WebResult(name = "PingResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "Ping", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.Ping")
    @ResponseWrapper(localName = "PingResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.PingResponse")
    public boolean ping();

    /**
     * @param activateEnvelope
     * @param envelopeInformation
     * @param recipients
     * @param templateReferences
     * @return returns com.docusign.model.EnvelopeStatus
     */
    @WebMethod(operationName = "CreateEnvelopeFromTemplates", action = "http://www.docusign.net/API/3.0/CreateEnvelopeFromTemplates")
    @WebResult(name = "CreateEnvelopeFromTemplatesResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "CreateEnvelopeFromTemplates", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.CreateEnvelopeFromTemplates")
    @ResponseWrapper(localName = "CreateEnvelopeFromTemplatesResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.CreateEnvelopeFromTemplatesResponse")
    public EnvelopeStatus createEnvelopeFromTemplates(
            @WebParam(name = "TemplateReferences", targetNamespace = "http://www.docusign.net/API/3.0")
            ArrayOfTemplateReference templateReferences,
            @WebParam(name = "Recipients", targetNamespace = "http://www.docusign.net/API/3.0")
            ArrayOfRecipient1 recipients,
            @WebParam(name = "EnvelopeInformation", targetNamespace = "http://www.docusign.net/API/3.0")
            EnvelopeInformation envelopeInformation,
            @WebParam(name = "ActivateEnvelope", targetNamespace = "http://www.docusign.net/API/3.0")
            boolean activateEnvelope);

    /**
     * @param activateEnvelope
     * @param envelopeInformation
     * @param compositeTemplates
     * @return returns com.docusign.model.EnvelopeStatus
     */
    @WebMethod(operationName = "CreateEnvelopeFromTemplatesAndForms", action = "http://www.docusign.net/API/3.0/CreateEnvelopeFromTemplatesAndForms")
    @WebResult(name = "CreateEnvelopeFromTemplatesAndFormsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "CreateEnvelopeFromTemplatesAndForms", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.CreateEnvelopeFromTemplatesAndForms")
    @ResponseWrapper(localName = "CreateEnvelopeFromTemplatesAndFormsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.CreateEnvelopeFromTemplatesAndFormsResponse")
    public EnvelopeStatus createEnvelopeFromTemplatesAndForms(
            @WebParam(name = "EnvelopeInformation", targetNamespace = "http://www.docusign.net/API/3.0")
            EnvelopeInformation envelopeInformation,
            @WebParam(name = "CompositeTemplates", targetNamespace = "http://www.docusign.net/API/3.0")
            ArrayOfCompositeTemplate compositeTemplates,
            @WebParam(name = "ActivateEnvelope", targetNamespace = "http://www.docusign.net/API/3.0")
            boolean activateEnvelope);

    /**
     * @param envelopeID
     * @return returns com.docusign.model.DocuSignEnvelopeInformation
     */
    @WebMethod(operationName = "GetStatusInDocuSignConnectFormat", action = "http://www.docusign.net/API/3.0/GetStatusInDocuSignConnectFormat")
    @WebResult(name = "GetStatusInDocuSignConnectFormatResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "GetStatusInDocuSignConnectFormat", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.GetStatusInDocuSignConnectFormat")
    @ResponseWrapper(localName = "GetStatusInDocuSignConnectFormatResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.GetStatusInDocuSignConnectFormatResponse")
    public DocuSignEnvelopeInformation getStatusInDocuSignConnectFormat(
            @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
            String envelopeID);

    /**
     * @param envelopeID
     * @return returns com.docusign.model.PurgeDocumentStatus
     */
    @WebMethod(operationName = "PurgeDocuments", action = "http://www.docusign.net/API/3.0/PurgeDocuments")
    @WebResult(name = "PurgeDocumentsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "PurgeDocuments", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.PurgeDocuments")
    @ResponseWrapper(localName = "PurgeDocumentsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.PurgeDocumentsResponse")
    public PurgeDocumentStatus purgeDocuments(
            @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
            String envelopeID);

    /**
     * @param envelopeTemplate
     * @return returns com.docusign.model.SaveTemplateResult
     */
    @WebMethod(operationName = "SaveTemplate", action = "http://www.docusign.net/API/3.0/SaveTemplate")
    @WebResult(name = "SaveTemplateResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "SaveTemplate", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.SaveTemplate")
    @ResponseWrapper(localName = "SaveTemplateResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.SaveTemplateResponse")
    public SaveTemplateResult saveTemplate(
            @WebParam(name = "EnvelopeTemplate", targetNamespace = "http://www.docusign.net/API/3.0")
            EnvelopeTemplate envelopeTemplate);

    /**
     * @param shared
     * @param accountID
     * @param templateXML
     * @return returns com.docusign.model.SaveTemplateResult
     */
    @WebMethod(operationName = "UploadTemplate", action = "http://www.docusign.net/API/3.0/UploadTemplate")
    @WebResult(name = "UploadTemplateResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "UploadTemplate", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.UploadTemplate")
    @ResponseWrapper(localName = "UploadTemplateResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.UploadTemplateResponse")
    public SaveTemplateResult uploadTemplate(
            @WebParam(name = "TemplateXML", targetNamespace = "http://www.docusign.net/API/3.0")
            String templateXML,
            @WebParam(name = "AccountID", targetNamespace = "http://www.docusign.net/API/3.0")
            String accountID,
            @WebParam(name = "Shared", targetNamespace = "http://www.docusign.net/API/3.0")
            boolean shared);

    /**
     * @param accountID
     * @param includeAdvancedTemplates
     * @return returns com.docusign.model.EnvelopeTemplates
     */
    @WebMethod(operationName = "RequestTemplates", action = "http://www.docusign.net/API/3.0/RequestTemplates")
    @WebResult(name = "RequestTemplatesResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestTemplates", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestTemplates")
    @ResponseWrapper(localName = "RequestTemplatesResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestTemplatesResponse")
    public EnvelopeTemplates requestTemplates(
            @WebParam(name = "AccountID", targetNamespace = "http://www.docusign.net/API/3.0")
            String accountID,
            @WebParam(name = "IncludeAdvancedTemplates", targetNamespace = "http://www.docusign.net/API/3.0")
            boolean includeAdvancedTemplates);

    /**
     * @param templateID
     * @param includeDocumentBytes
     * @return returns com.docusign.model.EnvelopeTemplate
     */
    @WebMethod(operationName = "RequestTemplate", action = "http://www.docusign.net/API/3.0/RequestTemplate")
    @WebResult(name = "RequestTemplateResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestTemplate", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestTemplate")
    @ResponseWrapper(localName = "RequestTemplateResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestTemplateResponse")
    public EnvelopeTemplate requestTemplate(
            @WebParam(name = "TemplateID", targetNamespace = "http://www.docusign.net/API/3.0")
            String templateID,
            @WebParam(name = "IncludeDocumentBytes", targetNamespace = "http://www.docusign.net/API/3.0")
            boolean includeDocumentBytes);

    /**
     * @param templateIDs
     * @param includeDocumentBytes
     * @return returns com.docusign.model.ArrayOfEnvelopeTemplate
     */
    @WebMethod(operationName = "RequestTemplateList", action = "http://www.docusign.net/API/3.0/RequestTemplateList")
    @WebResult(name = "RequestTemplateListResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestTemplateList", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestTemplateList")
    @ResponseWrapper(localName = "RequestTemplateListResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestTemplateListResponse")
    public ArrayOfEnvelopeTemplate requestTemplateList(
            @WebParam(name = "TemplateIDs", targetNamespace = "http://www.docusign.net/API/3.0")
            ArrayOfString5 templateIDs,
            @WebParam(name = "IncludeDocumentBytes", targetNamespace = "http://www.docusign.net/API/3.0")
            boolean includeDocumentBytes);

    /**
     * @param templateID
     * @param includeDocumentBytes
     * @return returns com.docusign.model.EnvelopeTemplate
     */
    @WebMethod(operationName = "RequestTemplateWithDocumentFields", action = "http://www.docusign.net/API/3.0/RequestTemplateWithDocumentFields")
    @WebResult(name = "RequestTemplateWithDocumentFieldsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestTemplateWithDocumentFields", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestTemplateWithDocumentFields")
    @ResponseWrapper(localName = "RequestTemplateWithDocumentFieldsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestTemplateWithDocumentFieldsResponse")
    public EnvelopeTemplate requestTemplateWithDocumentFields(
            @WebParam(name = "TemplateID", targetNamespace = "http://www.docusign.net/API/3.0")
            String templateID,
            @WebParam(name = "IncludeDocumentBytes", targetNamespace = "http://www.docusign.net/API/3.0")
            boolean includeDocumentBytes);

    /**
     * @param templateIDs
     * @param includeDocumentBytes
     * @return returns com.docusign.model.ArrayOfEnvelopeTemplate
     */
    @WebMethod(operationName = "RequestTemplateListWithDocumentFields", action = "http://www.docusign.net/API/3.0/RequestTemplateListWithDocumentFields")
    @WebResult(name = "RequestTemplateListWithDocumentFieldsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestTemplateListWithDocumentFields", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestTemplateListWithDocumentFields")
    @ResponseWrapper(localName = "RequestTemplateListWithDocumentFieldsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestTemplateListWithDocumentFieldsResponse")
    public ArrayOfEnvelopeTemplate requestTemplateListWithDocumentFields(
            @WebParam(name = "TemplateIDs", targetNamespace = "http://www.docusign.net/API/3.0")
            ArrayOfString5 templateIDs,
            @WebParam(name = "IncludeDocumentBytes", targetNamespace = "http://www.docusign.net/API/3.0")
            boolean includeDocumentBytes);

    /**
     * @param goToEnvelopeID
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "GetAuthenticationToken", action = "http://www.docusign.net/API/3.0/GetAuthenticationToken")
    @WebResult(name = "GetAuthenticationTokenResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "GetAuthenticationToken", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.GetAuthenticationToken")
    @ResponseWrapper(localName = "GetAuthenticationTokenResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.GetAuthenticationTokenResponse")
    public String getAuthenticationToken(
            @WebParam(name = "GoToEnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
            String goToEnvelopeID);

    /**
     * @param accountID
     * @return returns com.docusign.model.ArrayOfAddressBookItem
     */
    @WebMethod(operationName = "GetAddressBookItems", action = "http://www.docusign.net/API/3.0/GetAddressBookItems")
    @WebResult(name = "GetAddressBookItemsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "GetAddressBookItems", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.GetAddressBookItems")
    @ResponseWrapper(localName = "GetAddressBookItemsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.GetAddressBookItemsResponse")
    public ArrayOfAddressBookItem getAddressBookItems(
            @WebParam(name = "AccountID", targetNamespace = "http://www.docusign.net/API/3.0")
            String accountID);

    /**
     * @param returnAddressBook
     * @param addressBookItems
     * @return returns com.docusign.model.UpdateAddressBookResult
     */
    @WebMethod(operationName = "UpdateAddressBookItems", action = "http://www.docusign.net/API/3.0/UpdateAddressBookItems")
    @WebResult(name = "UpdateAddressBookItemsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "UpdateAddressBookItems", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.UpdateAddressBookItems")
    @ResponseWrapper(localName = "UpdateAddressBookItemsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.UpdateAddressBookItemsResponse")
    public UpdateAddressBookResult updateAddressBookItems(
            @WebParam(name = "AddressBookItems", targetNamespace = "http://www.docusign.net/API/3.0")
            ArrayOfAddressBookItem addressBookItems,
            @WebParam(name = "ReturnAddressBook", targetNamespace = "http://www.docusign.net/API/3.0")
            boolean returnAddressBook);

    /**
     * @param returnAddressBook
     * @param addressBookRemoveItems
     * @return returns com.docusign.model.UpdateAddressBookResult
     */
    @WebMethod(operationName = "RemoveAddressBookItems", action = "http://www.docusign.net/API/3.0/RemoveAddressBookItems")
    @WebResult(name = "RemoveAddressBookItemsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RemoveAddressBookItems", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RemoveAddressBookItems")
    @ResponseWrapper(localName = "RemoveAddressBookItemsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RemoveAddressBookItemsResponse")
    public UpdateAddressBookResult removeAddressBookItems(
            @WebParam(name = "AddressBookRemoveItems", targetNamespace = "http://www.docusign.net/API/3.0")
            ArrayOfAddressBookRemoveItem addressBookRemoveItems,
            @WebParam(name = "ReturnAddressBook", targetNamespace = "http://www.docusign.net/API/3.0")
            boolean returnAddressBook);

    /**
     * @param accountID
     * @param block
     * @param transactionID
     * @return returns com.docusign.model.SynchEnvelopeStatus
     */
    @WebMethod(operationName = "SynchEnvelope", action = "http://www.docusign.net/API/3.0/SynchEnvelope")
    @WebResult(name = "SynchEnvelopeResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "SynchEnvelope", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.SynchEnvelope")
    @ResponseWrapper(localName = "SynchEnvelopeResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.SynchEnvelopeResponse")
    public SynchEnvelopeStatus synchEnvelope(
            @WebParam(name = "TransactionID", targetNamespace = "http://www.docusign.net/API/3.0")
            String transactionID,
            @WebParam(name = "AccountID", targetNamespace = "http://www.docusign.net/API/3.0")
            String accountID,
            @WebParam(name = "Block", targetNamespace = "http://www.docusign.net/API/3.0")
            boolean block);

    /**
     * @param accountID
     * @param envelopeID
     * @param returnURL
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "RequestSenderToken", action = "http://www.docusign.net/API/3.0/RequestSenderToken")
    @WebResult(name = "RequestSenderTokenResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestSenderToken", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestSenderToken")
    @ResponseWrapper(localName = "RequestSenderTokenResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestSenderTokenResponse")
    public String requestSenderToken(
            @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
            String envelopeID,
            @WebParam(name = "AccountID", targetNamespace = "http://www.docusign.net/API/3.0")
            String accountID,
            @WebParam(name = "ReturnURL", targetNamespace = "http://www.docusign.net/API/3.0")
            String returnURL);

    /**
     * @param suppressNavigation
     * @param envelopeID
     * @param returnURL
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "RequestCorrectToken", action = "http://www.docusign.net/API/3.0/RequestCorrectToken")
    @WebResult(name = "RequestCorrectTokenResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestCorrectToken", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestCorrectToken")
    @ResponseWrapper(localName = "RequestCorrectTokenResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestCorrectTokenResponse")
    public String requestCorrectToken(
            @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
            String envelopeID,
            @WebParam(name = "SuppressNavigation", targetNamespace = "http://www.docusign.net/API/3.0")
            boolean suppressNavigation,
            @WebParam(name = "ReturnURL", targetNamespace = "http://www.docusign.net/API/3.0")
            String returnURL);

    /**
     * @param folderFilter
     * @return returns com.docusign.model.FolderResults
     */
    @WebMethod(operationName = "GetFolderItems", action = "http://www.docusign.net/API/3.0/GetFolderItems")
    @WebResult(name = "GetFolderItemsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "GetFolderItems", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.GetFolderItems")
    @ResponseWrapper(localName = "GetFolderItemsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.GetFolderItemsResponse")
    public FolderResults getFolderItems(
            @WebParam(name = "FolderFilter", targetNamespace = "http://www.docusign.net/API/3.0")
            FolderFilter folderFilter);

    /**
     * @param foldersFilter
     * @return returns com.docusign.model.AvailableFolders
     */
    @WebMethod(operationName = "GetFolderList", action = "http://www.docusign.net/API/3.0/GetFolderList")
    @WebResult(name = "GetFolderListResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "GetFolderList", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.GetFolderList")
    @ResponseWrapper(localName = "GetFolderListResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.GetFolderListResponse")
    public AvailableFolders getFolderList(
            @WebParam(name = "FoldersFilter", targetNamespace = "http://www.docusign.net/API/3.0")
            FoldersFilter foldersFilter);

    /**
     * @param arg
     * @return returns boolean
     */
    @WebMethod(operationName = "MoveEnvelopes", action = "http://www.docusign.net/API/3.0/MoveEnvelopes")
    @WebResult(name = "MoveEnvelopesResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "MoveEnvelopes", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.MoveEnvelopes")
    @ResponseWrapper(localName = "MoveEnvelopesResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.MoveEnvelopesResponse")
    public boolean moveEnvelopes(
            @WebParam(name = "Arg", targetNamespace = "http://www.docusign.net/API/3.0")
            MoveEnvelopesArg arg);

    /**
     * @param arg
     * @return returns boolean
     */
    @WebMethod(operationName = "DeleteEnvelopes", action = "http://www.docusign.net/API/3.0/DeleteEnvelopes")
    @WebResult(name = "DeleteEnvelopesResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "DeleteEnvelopes", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.DeleteEnvelopes")
    @ResponseWrapper(localName = "DeleteEnvelopesResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.DeleteEnvelopesResponse")
    public boolean deleteEnvelopes(
            @WebParam(name = "Arg", targetNamespace = "http://www.docusign.net/API/3.0")
            DeleteEnvelopesArg arg);

    /**
     * @param arg
     * @param accountId
     * @return returns com.docusign.model.CaptiveRecipientResults
     */
    @WebMethod(operationName = "DeleteCaptiveRecipientsSignatures", action = "http://www.docusign.net/API/3.0/DeleteCaptiveRecipientsSignatures")
    @WebResult(name = "DeleteCaptiveRecipientsSignaturesResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "DeleteCaptiveRecipientsSignatures", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.DeleteCaptiveRecipientsSignatures")
    @ResponseWrapper(localName = "DeleteCaptiveRecipientsSignaturesResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.DeleteCaptiveRecipientsSignaturesResponse")
    public CaptiveRecipientResults deleteCaptiveRecipientsSignatures(
            @WebParam(name = "AccountId", targetNamespace = "http://www.docusign.net/API/3.0")
            String accountId,
            @WebParam(name = "Arg", targetNamespace = "http://www.docusign.net/API/3.0")
            DeleteCaptiveRecipientsSignaturesArg arg);

    /**
     * @param envelopeID
     * @param includeDocumentBytes
     * @return returns com.docusign.model.Envelope
     */
    @WebMethod(operationName = "RequestEnvelope", action = "http://www.docusign.net/API/3.0/RequestEnvelope")
    @WebResult(name = "RequestEnvelopeResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestEnvelope", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestEnvelope")
    @ResponseWrapper(localName = "RequestEnvelopeResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestEnvelopeResponse")
    public Envelope requestEnvelope(
            @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
            String envelopeID,
            @WebParam(name = "IncludeDocumentBytes", targetNamespace = "http://www.docusign.net/API/3.0")
            boolean includeDocumentBytes);

    /**
     * @param envelopeID
     * @param includeDocumentBytes
     * @return returns com.docusign.model.Envelope
     */
    @WebMethod(operationName = "RequestEnvelopeWithDocumentFields", action = "http://www.docusign.net/API/3.0/RequestEnvelopeWithDocumentFields")
    @WebResult(name = "RequestEnvelopeWithDocumentFieldsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestEnvelopeWithDocumentFields", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestEnvelopeWithDocumentFields")
    @ResponseWrapper(localName = "RequestEnvelopeWithDocumentFieldsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.RequestEnvelopeWithDocumentFieldsResponse")
    public Envelope requestEnvelopeWithDocumentFields(
            @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
            String envelopeID,
            @WebParam(name = "IncludeDocumentBytes", targetNamespace = "http://www.docusign.net/API/3.0")
            boolean includeDocumentBytes);

    /**
     * @param connectFailuresFilter
     * @return returns com.docusign.model.ArrayOfConnectFailure
     */
    @WebMethod(operationName = "GetConnectFailures", action = "http://www.docusign.net/API/3.0/GetConnectFailures")
    @WebResult(name = "GetConnectFailuresResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "GetConnectFailures", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.GetConnectFailures")
    @ResponseWrapper(localName = "GetConnectFailuresResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.GetConnectFailuresResponse")
    public ArrayOfConnectFailure getConnectFailures(
            @WebParam(name = "ConnectFailuresFilter", targetNamespace = "http://www.docusign.net/API/3.0")
            ConnectFailuresFilter connectFailuresFilter);

    /**
     * @param publishConnectFailuresFilter
     * @return returns com.docusign.model.ArrayOfPublishConnectFailuresResult
     */
    @WebMethod(operationName = "PublishConnectFailures", action = "http://www.docusign.net/API/3.0/PublishConnectFailures")
    @WebResult(name = "PublishConnectFailuresResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "PublishConnectFailures", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.PublishConnectFailures")
    @ResponseWrapper(localName = "PublishConnectFailuresResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "com.docusign.model.PublishConnectFailuresResponse")
    public ArrayOfPublishConnectFailuresResult publishConnectFailures(
            @WebParam(name = "PublishConnectFailuresFilter", targetNamespace = "http://www.docusign.net/API/3.0")
            PublishConnectFailuresFilter publishConnectFailuresFilter);

}
